import type { UserRole } from "@/types/roles";

/**
 * Keeps links generated by shared screens inside the workspace currently
 * being viewed. Admin screens may reuse organizer components, but their links
 * must remain in the admin namespace.
 */
export function getWorkspaceRoute(pathname: string, organizerRoute: string, adminRoute: string) {
  return pathname.startsWith("/admin") ? adminRoute : organizerRoute;
}

export function getWorkspaceProfileRoute(role: UserRole) {
  return role === "admin" ? "/admin/profile" : role === "organizer" ? "/organizer/profile" : "/profile";
}
