export const APP_ROUTES = {
  accessDenied: "/access-denied",
  dashboard: "/dashboard",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  terms: "/terms",
  privacy: "/privacy",
  profile: "/profile",
  notifications: "/notifications",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminUsers: "/admin/users",
  adminEvents: "/admin/events",
  adminCreateEvent: "/admin/events/create",
  adminAttendance: "/admin/attendance",
  adminCredentials: "/admin/credentials",
  adminReports: "/admin/reports",
  adminAnalytics: "/admin/analytics",
  adminAuditLogs: "/admin/audit-logs",
  adminCatalogs: "/admin/catalogs",
  adminSettings: "/admin/settings",
  adminSystemHealth: "/admin/system-health",
  adminProfile: "/admin/profile",
  departmentUsers: "/department/users",
  department: "/department",
  departmentDashboard: "/department/dashboard",
  departmentEvents: "/department/events",
  departmentCredentials: "/department/credentials",
  departmentRecords: "/department/records",
  departmentStudents: "/department/students",
  departmentAttendance: "/department/attendance",
  departmentAnalytics: "/department/analytics",
  departmentReports: "/department/reports",
  departmentAuditLogs: "/department/audit-logs",
  departmentSystemHealth: "/department/system-health",
  departmentSettings: "/department/settings",
  departmentBranding: "/department/branding",
  departmentProfile: "/department/profile",
  organizer: "/organizer",
  organizerDashboard: "/organizer/dashboard",
  organizerEvents: "/organizer/events",
  organizerCreateEvent: "/organizer/events/create",
  organizerUsers: "/organizer/users",
  organizerRecords: "/organizer/records",
  organizerReports: "/organizer/reports",
  organizerCredentials: "/organizer/credentials",
  organizerAnalytics: "/organizer/analytics",
  organizerCorrections: "/organizer/corrections",
  organizerProfile: "/organizer/profile",
  organizerSettings: "/organizer/settings",
  organizerAuditLogs: "/organizer/audit-logs",
  organizerEvent: (eventId: string) => `/organizer/events/${eventId}`,
  organizerLiveAttendance: "/organizer/live-attendance",
  organizerLiveSession: (sessionId: string) => `/organizer/events?session=${encodeURIComponent(sessionId)}`,
  adminEvent: (eventId: string) => `/admin/events/${eventId}`,
  adminLiveSession: (sessionId: string) => `/admin/events?session=${encodeURIComponent(sessionId)}`,
  student: "/student",
  studentDashboard: "/student/dashboard",
  studentSchedule: "/student/schedule",
  studentUpcomingEvents: "/student/events",
  studentEvent: (eventId: string) => `/student/events/${eventId}`,
  studentAttendance: "/student/attendance",
  studentMethods: "/student/methods",
  studentRequestHistory: "/student/request-history",
  studentCorrections: "/student/corrections",
  studentFaqs: "/student/faqs",
  studentProfile: "/student/profile",
  studentLegalReview: "/student/legal-review"
} as const;
