export const APP_ROUTES = {
  accessDenied: "/access-denied",
  dashboard: "/dashboard",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/profile",
  notifications: "/notifications",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminUsers: "/admin/users",
  adminEvents: "/admin/events",
  adminAttendance: "/admin/attendance",
  adminCorrections: "/admin/corrections",
  adminCredentials: "/admin/credentials",
  adminReports: "/admin/reports",
  adminAnalytics: "/admin/analytics",
  adminAuditLogs: "/admin/audit-logs",
  adminCatalogs: "/admin/catalogs",
  adminSettings: "/admin/settings",
  adminProfile: "/admin/profile",
  organizer: "/organizer",
  organizerDashboard: "/organizer/dashboard",
  organizerEvents: "/organizer/events",
  organizerCreateEvent: "/organizer/events/create",
  organizerUsers: "/organizer/users",
  organizerRecords: "/organizer/records",
  organizerReports: "/organizer/reports",
  organizerAnalytics: "/organizer/analytics",
  organizerCorrections: "/organizer/corrections",
  organizerProfile: "/organizer/profile",
  organizerSettings: "/organizer/settings",
  organizerAuditLogs: "/organizer/audit-logs",
  organizerEvent: (eventId: string) => `/organizer/events/${eventId}`,
  organizerLiveSession: (sessionId: string) => `/organizer/events?session=${encodeURIComponent(sessionId)}`,
  student: "/student",
  studentDashboard: "/student/dashboard",
  studentSchedule: "/student/schedule",
  studentUpcomingEvents: "/student/events",
  studentEvent: (eventId: string) => `/student/events/${eventId}`,
  studentAttendance: "/student/attendance",
  studentMethods: "/student/methods",
  studentRequestHistory: "/student/request-history",
  studentCorrections: "/student/corrections",
  studentProfile: "/student/profile"
} as const;
