import { beforeEach, describe, expect, it, vi } from "vitest";
import { reconcileOfflineEventLifecycle, synchronizePendingAttendance } from "@/features/offline/offlineService";
import type { PendingAttendanceRecord, PLPassDesktopApi } from "@/features/offline/types";

const rpc=vi.fn(); const maybeSingle=vi.fn(); const getUser=vi.fn();
vi.mock("@/lib/supabase/client",()=>({getSupabaseBrowserClient:()=>({auth:{getUser},rpc,from:()=>({select:()=>({eq:()=>({maybeSingle})})})})}));
const record:PendingAttendanceRecord={localAttendanceUuid:"local-1",eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr",attendanceTimestamp:"2026-09-05T00:15:00.000Z",attendanceStatus:"present",timeIn:"2026-09-05T00:15:00.000Z",syncStatus:"PENDING_SYNC",syncAttempts:0,createdAt:"2026-09-05T00:15:00.000Z",updatedAt:"2026-09-05T00:15:00.000Z"};
function api(){return {recoverInterruptedSync:vi.fn().mockResolvedValue(0),beginSync:vi.fn().mockResolvedValue([record]),confirmSync:vi.fn().mockResolvedValue(undefined),failSync:vi.fn().mockResolvedValue(undefined),hasUnresolvedWork:vi.fn().mockResolvedValue(false),listPending:vi.fn().mockResolvedValue([]),beginWalkInSync:vi.fn().mockResolvedValue([]),listPendingWalkInScans:vi.fn().mockResolvedValue([]),confirmWalkInSync:vi.fn().mockResolvedValue(undefined),failWalkInSync:vi.fn().mockResolvedValue(undefined)} as unknown as PLPassDesktopApi;}
describe("offline synchronization",()=>{beforeEach(()=>{vi.clearAllMocks();getUser.mockResolvedValue({data:{user:{id:"organizer"}},error:null});});
  it("confirms an idempotent upload with a bounded batch",async()=>{const local=api();window.plpassDesktop=local;rpc.mockResolvedValue({data:{id:"server-1",local_attendance_uuid:"local-1"},error:null});expect(await synchronizePendingAttendance(1000,false,false,"organizer")).toEqual({confirmed:1,failed:0});expect(local.beginSync).toHaveBeenCalledWith(20,false,"organizer");expect(local.confirmSync).toHaveBeenCalledWith("local-1","server-1");});
  it("recovers a lost success response by querying the UUID",async()=>{const local=api();window.plpassDesktop=local;rpc.mockRejectedValue(new Error("response lost"));maybeSingle.mockResolvedValue({data:{id:"server-1",local_attendance_uuid:"local-1"}});expect(await synchronizePendingAttendance(20,false,false,"organizer")).toEqual({confirmed:1,failed:0});expect(local.failSync).not.toHaveBeenCalled();});
  it("retains network failures for retry",async()=>{const local=api();window.plpassDesktop=local;rpc.mockResolvedValue({data:null,error:{code:"NETWORK"}});maybeSingle.mockRejectedValue(new Error("offline"));expect(await synchronizePendingAttendance(20,false,false,"organizer")).toEqual({confirmed:0,failed:1});expect(local.failSync).toHaveBeenCalledWith("local-1","RETRY",expect.any(String));});
  it("backs off a server throttle without issuing a follow-up attendance query",async()=>{const local=api();window.plpassDesktop=local;rpc.mockResolvedValue({data:null,error:null});expect(await synchronizePendingAttendance(20,true,false,"organizer")).toEqual({confirmed:0,failed:1});expect(local.failSync).toHaveBeenCalledWith("local-1","RETRY",expect.stringContaining("rate limited"));expect(maybeSingle).not.toHaveBeenCalled();});
  it("retains genuine central conflicts and backs off retries",async()=>{const local=api();window.plpassDesktop=local;rpc.mockResolvedValue({data:null,error:{code:"40001"}});maybeSingle.mockResolvedValue({data:null});await synchronizePendingAttendance(20,true,false,"organizer");expect(local.failSync).toHaveBeenCalledWith("local-1","CONFLICT",expect.any(String));const beginCalls=vi.mocked(local.beginSync).mock.calls.length;expect(await synchronizePendingAttendance(20,false,false,"organizer")).toEqual({confirmed:0,failed:0});expect(local.beginSync).toHaveBeenCalledTimes(beginCalls);});
  it("does not retry permanent authorization failures",async()=>{const local=api();window.plpassDesktop=local;rpc.mockResolvedValue({data:null,error:{code:"42501",message:"An active organizer account is required."}});maybeSingle.mockResolvedValue({data:null});await synchronizePendingAttendance(20,true,false,"organizer");expect(local.failSync).toHaveBeenCalledWith("local-1","CONFLICT",expect.any(String));const beginCalls=vi.mocked(local.beginSync).mock.calls.length;expect(await synchronizePendingAttendance(20,false,false,"organizer")).toEqual({confirmed:0,failed:0});expect(local.beginSync).toHaveBeenCalledTimes(beginCalls);});
  it("lets an explicit retry bypass automatic backoff",async()=>{const local=api();window.plpassDesktop=local;rpc.mockResolvedValueOnce({data:null,error:{code:"NETWORK"}}).mockResolvedValueOnce({data:{id:"server-1",local_attendance_uuid:"local-1"},error:null});maybeSingle.mockResolvedValue({data:null});await synchronizePendingAttendance(20,true,false,"organizer");expect(await synchronizePendingAttendance(20,true,false,"organizer")).toEqual({confirmed:1,failed:0});expect(local.beginSync).toHaveBeenCalledTimes(2);});
  it("reconciles an offline start, then ends only with the exact prepared roster",async()=>{
    const session={id:"session-1",eventId:"event-1",title:"Event",venue:"Hall",status:"completed",startsAt:"2026-09-05T00:00:00.000Z",endsAt:"2026-09-05T03:00:00.000Z",offlineLifecycle:"END_PENDING",offlineStartedAt:"2026-09-05T00:15:00.000Z",offlineEndedAt:"2026-09-05T02:00:00.000Z",offlineStartReconciledAt:"2026-09-05T00:16:00.000Z"};
    const pkg={event:{id:"event-1",code:"EVT-1",title:"Event",status:"scheduled",startsAt:session.startsAt,endsAt:session.endsAt},sessions:[session],participants:[{studentId:"student-1",studentNumber:"S1",displayName:"Student One",participantStatus:"active",faceEmbeddings:[]},{studentId:"student-2",studentNumber:"S2",displayName:"Student Two",participantStatus:"active",faceEmbeddings:[]}],attendance:[]} ;
    const local={...api(),listPreparedEvents:vi.fn().mockResolvedValue([{event:pkg.event,sessionId:"session-1",lifecycle:"END_PENDING"}]),getPreparedEvent:vi.fn().mockResolvedValue(pkg),setOfflineLifecycleState:vi.fn().mockResolvedValue(undefined),listPending:vi.fn().mockResolvedValue([]),listPendingWalkInScans:vi.fn().mockResolvedValue([]),beginSync:vi.fn().mockResolvedValue([])} as unknown as PLPassDesktopApi;
    window.plpassDesktop=local;
    rpc.mockResolvedValue({data:{id:"session-1"},error:null});
    expect(await reconcileOfflineEventLifecycle("organizer",true)).toMatchObject({completed:true});
    expect(rpc).toHaveBeenCalledWith("reconcile_offline_event_session_end",{p_session_id:"session-1",p_actual_end:session.offlineEndedAt,p_reason:"Organizer ended this session offline.",p_expected_student_ids:["student-1","student-2"]});
    expect(rpc).not.toHaveBeenCalledWith("reconcile_offline_event_session_start",expect.anything());
    expect(local.setOfflineLifecycleState).toHaveBeenCalledWith("event-1","session-1","ENDED");
  });
  it("uploads pending attendance for a session already marked STARTED during global reconnect",async()=>{
    const local=api();
    local.listPreparedEvents=vi.fn().mockResolvedValue([{event:{id:"event-1",code:"EVT-1",title:"Event",status:"ongoing",startsAt:record.createdAt,endsAt:record.createdAt},sessionId:"session-1",lifecycle:"STARTED",preparedAt:record.createdAt,cacheVersion:1}]);
    window.plpassDesktop=local;
    rpc.mockResolvedValue({data:{id:"server-1",local_attendance_uuid:"local-1"},error:null});
    expect(await reconcileOfflineEventLifecycle("organizer",true)).toMatchObject({completed:true});
    expect(rpc).toHaveBeenCalledWith("sync_offline_event_attendance",expect.objectContaining({p_local_attendance_uuid:"local-1"}));
    expect(local.confirmSync).toHaveBeenCalledWith("local-1","server-1");
  });
});
