import { DatabaseSync } from "node:sqlite";
import { describe, expect, it } from "vitest";
import { LocalAttendanceDatabase } from "../electron/localDatabase";
import type { PreparedEventPackage } from "@/features/offline/types";

function eventPackage():PreparedEventPackage{return {cacheVersion:1,preparedAt:"2026-09-05T00:00:00.000Z",event:{id:"event-1",code:"EVT-1",title:"Prepared Event",status:"ongoing",startsAt:"2026-09-05T00:00:00.000Z",endsAt:"2026-09-05T08:00:00.000Z"},sessions:[{id:"session-1",eventId:"event-1",title:"Main",venue:"Hall",status:"ongoing",startsAt:"2026-09-05T00:00:00.000Z",endsAt:"2026-09-05T08:00:00.000Z",lateCutoffAt:"2026-09-05T01:00:00.000Z"}],participants:[{studentId:"student-1",studentNumber:"2026-001",displayName:"Ada Student",participantStatus:"confirmed",qrIdentifier:"qr-1",faceEmbeddings:[[1,0,0]]}],attendance:[]};}
function setup(){return new LocalAttendanceDatabase(new DatabaseSync(":memory:"));}

describe("temporary event database",()=>{
  it("prepares and refreshes a complete event package",()=>{const store=setup();expect(store.prepareEvent(eventPackage()).packageStatus).toBe("READY");const refreshed=eventPackage();refreshed.preparedAt="2026-09-05T00:30:00.000Z";expect(store.prepareEvent(refreshed).preparedAt).toBe(refreshed.preparedAt);expect(store.identifyQr("event-1","qr-1")?.studentId).toBe("student-1");expect(store.identifyManual("event-1","2026-001")?.displayName).toBe("Ada Student");});
  it("rejects an incomplete package",()=>{const store=setup();const pkg=eventPackage();pkg.participants=[];expect(()=>store.prepareEvent(pkg)).toThrow(/incomplete/i);expect(store.getStatus("event-1").packageStatus).toBe("NOT_PREPARED");});
  it("stores a scheduled package before the event without accepting attendance",()=>{const store=setup();const pkg=eventPackage();pkg.event.status="scheduled";pkg.sessions[0].status="scheduled";expect(store.prepareEvent(pkg).packageStatus).toBe("READY");expect(()=>store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr",attendanceTimestamp:"2026-09-05T00:15:00.000Z"})).toThrow(/no active prepared event session/i);});
  it("keeps an ongoing session open after its original scheduled end time",()=>{const store=setup();const pkg=eventPackage();pkg.sessions[0].endsAt="2026-09-05T00:10:00.000Z";pkg.sessions[0].attendanceWindowEndAt=undefined;store.prepareEvent(pkg);expect(store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr",attendanceTimestamp:"2026-09-05T00:15:00.000Z"}).action).toBe("checked_in");});
  it.each(["qr","facial","manual"] as const)("uses shared validation and records %s attendance locally",(method)=>{const store=setup();store.prepareEvent(eventPackage());const result=store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:method,attendanceTimestamp:"2026-09-05T00:15:00.000Z"});expect(result.action).toBe("checked_in");expect(result.record.syncStatus).toBe("PENDING_SYNC");expect(result.safeMessage).toMatch(/synchronization is pending/i);});
  it("prevents local duplicates and supports one checkout",()=>{const store=setup();store.prepareEvent(eventPackage());const input={eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr" as const,attendanceTimestamp:"2026-09-05T00:15:00.000Z"};store.recordAttendance(input);expect(store.recordAttendance({...input,attendanceTimestamp:"2026-09-05T02:00:00.000Z"}).action).toBe("checked_out");expect(store.recordAttendance({...input,attendanceTimestamp:"2026-09-05T03:00:00.000Z"}).action).toBe("already_recorded");expect(store.listPending()).toHaveLength(1);});
  it("keeps scanner Time In and Time Out as explicit phases",()=>{const store=setup();store.prepareEvent(eventPackage());const input={eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr" as const,attendanceTimestamp:"2026-09-05T00:15:00.000Z"};expect(store.recordScannerCheckIn(input).action).toBe("checked_in");expect(store.recordScannerCheckIn({...input,attendanceTimestamp:"2026-09-05T00:17:00.000Z"}).action).toBe("already_recorded");expect(()=>store.recordScannerCheckOut({...input,attendanceTimestamp:"2026-09-05T00:15:30.000Z"})).toThrow(/one minute/i);expect(store.recordScannerCheckOut({...input,attendanceTimestamp:"2026-09-05T00:17:00.000Z"}).action).toBe("checked_out");expect(store.listPending()[0].timeOut).toBe("2026-09-05T00:17:00.000Z");});
  it("recovers interrupted syncing and retains conflicts",()=>{const store=setup();store.prepareEvent(eventPackage());store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"manual",attendanceTimestamp:"2026-09-05T00:15:00.000Z",remarks:"Badge unreadable"});const [record]=store.beginSync(20);expect(record.syncStatus).toBe("SYNCING");expect(store.recoverInterruptedSync()).toBe(1);expect(store.listPending()[0].syncStatus).toBe("RETRY");store.failSync(record.localAttendanceUuid,"CONFLICT","Central record differs");expect(store.listPending()[0].lastSyncError).toMatch(/differs/);});
  it("deletes attendance only after positive confirmation",()=>{const store=setup();store.prepareEvent(eventPackage());const record=store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr",attendanceTimestamp:"2026-09-05T00:15:00.000Z"}).record;store.failSync(record.localAttendanceUuid,"RETRY","Network unavailable");expect(store.listPending()).toHaveLength(1);store.confirmSync(record.localAttendanceUuid,"server-1");expect(store.listPending()).toHaveLength(0);});
  it("retains event and biometric cache after reconnect/sync",()=>{const store=setup();store.prepareEvent(eventPackage());const record=store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"facial",attendanceTimestamp:"2026-09-05T00:15:00.000Z"}).record;store.confirmSync(record.localAttendanceUuid,"server-1");expect(store.listFaceCandidates("event-1")).toHaveLength(1);expect(store.getStatus("event-1").packageStatus).toBe("READY");});
  it("blocks unsafe cleanup and removes the verified post-event biometric cache",()=>{const store=setup();store.prepareEvent(eventPackage());const record=store.recordAttendance({eventId:"event-1",sessionId:"session-1",studentId:"student-1",identificationMethod:"qr",attendanceTimestamp:"2026-09-05T00:15:00.000Z"}).record;expect(store.cleanupEvent("event-1",true,true).cleaned).toBe(false);store.confirmSync(record.localAttendanceUuid,"server-1");expect(store.cleanupEvent("event-1",false,true).message).toMatch(/verification/i);expect(store.cleanupEvent("event-1",true,true).cleaned).toBe(true);expect(store.listFaceCandidates("event-1")).toHaveLength(0);});
});
