-- Staging-only fixture. Create confirmed Auth users first:
-- plpass-concurrent-organizer@staging.invalid and plpass-concurrent-student@staging.invalid
do $$ declare ou uuid; su uuid; d uuid; p uuid; sec uuid; cat uuid; org uuid; stu uuid; ev uuid; day timestamp;
begin
 select id into ou from auth.users where email='plpass-concurrent-organizer@staging.invalid'; select id into su from auth.users where email='plpass-concurrent-student@staging.invalid'; if ou is null or su is null then raise exception 'Create the two synthetic Auth users first.'; end if; day:=date_trunc('day',now() at time zone 'Asia/Manila');
 insert into public.departments(department_code,department_name) values('STG-CW','Staging Concurrent Window') on conflict ((lower(department_code))) do update set department_name=excluded.department_name returning id into d;
 insert into public.programs(department_id,program_code,program_name) values(d,'STG-CW','Staging Concurrent Window') on conflict (department_id,(lower(program_code))) do update set program_name=excluded.program_name returning id into p;
 insert into public.sections(program_id,section_name,year_level,academic_year,semester) values(p,'CW',1,'2099-2100','Concurrent Window') on conflict (program_id,(lower(section_name)),academic_year,semester) do update set year_level=excluded.year_level returning id into sec;
 insert into public.profiles(id,email,first_name,last_name,role,account_status,department_id,employee_id,student_id) values(ou,'plpass-concurrent-organizer@staging.invalid','Synthetic','Concurrent Organizer','organizer','active',d,'STG-CW-ORG',null) on conflict(id) do update set role='organizer',account_status='active',department_id=d;
 insert into public.organizers(profile_id,employee_id,department_id,organization_name,position,organizer_status) values(ou,'STG-CW-ORG',d,'PLPass Staging','Concurrent Organizer','active') on conflict(profile_id) do update set organizer_status='active' returning id into org;
 insert into public.profiles(id,email,first_name,last_name,role,account_status,department_id,employee_id,student_id) values(su,'plpass-concurrent-student@staging.invalid','Synthetic','Concurrent Student','student','active',d,null,'STG-CW-1') on conflict(id) do update set role='student',account_status='active',department_id=d,student_id='STG-CW-1';
 insert into public.students(profile_id,student_id,program_id,department_id,section_id,year_level,student_status) values(su,'STG-CW-1',p,d,sec,1,'enrolled') on conflict(profile_id) do update set student_status='enrolled' returning id into stu;
 insert into public.event_categories(category_name) values('Staging Concurrent Window') on conflict ((lower(category_name))) do update set category_name=excluded.category_name returning id into cat;
 insert into public.events(event_code,organizer_id,department_id,category_id,title,description,venue,starts_at,ends_at,event_status,approval_status) values('STG-CONCURRENT-WINDOW',org,d,cat,'Staging Concurrent Window','Synthetic only','Staging Test Room',day at time zone 'Asia/Manila',(day+interval '23 hours 59 minutes') at time zone 'Asia/Manila','ongoing','approved') on conflict ((lower(event_code))) do update set organizer_id=org,department_id=d,category_id=cat,event_status='ongoing',approval_status='approved' returning id into ev;
 delete from public.event_sessions where event_id=ev; insert into public.event_sessions(event_id,session_name,venue,mode,session_status,scheduled_start,scheduled_end,actual_start,attendance_window_start_at,attendance_window_end_at,created_by) values(ev,'Concurrent Attendance','Staging Test Room','f2f','ongoing',day at time zone 'Asia/Manila',(day+interval '23 hours 59 minutes') at time zone 'Asia/Manila',now(),now(),(day+interval '23 hours 59 minutes') at time zone 'Asia/Manila',ou);
 insert into public.event_participants(event_id,student_id,participant_status) values(ev,stu,'confirmed') on conflict(event_id,student_id) do update set participant_status='confirmed';
end $$;
